sudo: required
dist: xenial
language: cpp
cache:
  ccache: true
git:
  depth: 1
addons:
  apt:
    packages:
      - cmake
      - libboost-filesystem-dev
      - libboost-iostreams-dev
      - libboost-thread-dev
      - libboost-chrono-dev
      - libeigen3-dev
      - libgtest-dev
      - libusb-1.0-0-dev
      - libqhull-dev
      - libvtk6-dev
      - libvtk6-qt-dev
      - libflann-dev
      - qtbase5-dev
      - libqt5opengl5-dev
      - libglew-dev
      - libopenni-dev
      - libproj-dev #missing dependency from vtk?
before_install:
  - bash .travis.sh before-install

jobs:
  include:
    - name: "Library, Examples, Tools, Apps"
      compiler: clang
      env: TASK="build"
      script: bash .travis.sh $TASK
    - name: "Unit Tests"
      compiler: gcc
      env: TASK="test"
      script: bash .travis.sh $TASK

notifications:
  email: false
